name: Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Crear hash de archivos shell
        id: shell-files-hash
        run: |
          HASH=$(find . -name "*.sh" -type f -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Configurar caché de shellcheck
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/bin/shellcheck
            ~/.cabal/bin/shellcheck
          key: ${{ runner.os }}-shellcheck-${{ steps.shell-files-hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-shellcheck-

      - name: Instalar shellcheck
        if: steps.cache-shellcheck.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Verificar sintaxis de scripts
        run: |
          for file in $(find . -name "*.sh"); do
            shellcheck "$file"
          done
