name: Links Markdown

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linkCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Instalar markdown-link-check
        run: npm install -g markdown-link-check

      - name: Verificar enlaces en archivos Markdown
        run: |
          EXIT_CODE=0
          for file in $(find . -name "*.md"); do
            echo "Verificando enlaces en $file"
            markdown-link-check --quiet "$file" || { echo "Error: Enlaces rotos encontrados en $file"; EXIT_CODE=1; }
          done
          exit $EXIT_CODE
