name: Links Markdown

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linkCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar markdown-link-check
        run: npm install -g markdown-link-check

      - name: Verificar enlaces en archivos Markdown
        run: |
          for file in $(find . -name "*.md"); do
            markdown-link-check "$file"
          done
